pub mod auth;
pub mod channel_format;
pub mod channel_reply;
pub mod extension;
pub mod channel_settings;
pub mod config_crypto;
pub mod claude_runner;
pub mod cost_telemetry;
pub mod cron_scheduler;
pub mod direct_api;
pub mod delegation;
pub mod discord;
pub mod discord_voice;
pub mod dispatcher;
pub mod evolution;
pub mod external_factors;
pub mod feature_gate;
pub mod handlers;
pub mod line;
pub mod media;
pub mod tts;
pub mod log;
pub mod gvu;
pub mod prediction;
pub mod protocol;
pub mod skill_lifecycle;
pub mod server;
pub mod session;
pub mod sticker;
pub mod task_spec;
pub mod telegram;
pub mod chat_commands;
pub mod defensive_prompt;
pub mod updater;
pub mod webchat;
pub mod webhook;
pub mod reminder_scheduler;
pub mod wiki_ingest;

// ── Hermes-learnings modules (Phase 3, 4, 6) ──
pub mod compression;
pub mod rl;
pub mod skill_extraction;
pub mod tool_classifier;

pub use extension::{GatewayExtension, NullExtension};
pub use server::{start_gateway, GatewayConfig};
