//! Split out of the pre-split `handlers.rs` (P12b). Pure movement.

#[allow(unused_imports)]
use super::*;

impl MethodHandler {
    pub(crate) fn handle_tools_catalog(&self, _params: Value) -> WsFrame {
        WsFrame::ok_response(
            "",
            json!({
                "tools": [
                    { "name": "agents.list", "description": "List all registered agents" },
                    { "name": "agents.status", "description": "Get agent status" },
                    { "name": "presets.list", "description": "WP-6F: list agent presets (\"職務組合\") under ~/.duduclaw/presets/" },
                    { "name": "presets.status", "description": "WP-6F: one agent's current preset binding + live resolution outcome (read-only, P1)" },
                    { "name": "agents.create", "description": "Create a new agent" },
                    { "name": "agents.delegate", "description": "Delegate a task" },
                    { "name": "agents.pause", "description": "Pause an agent" },
                    { "name": "agents.resume", "description": "Resume an agent" },
                    { "name": "agents.update", "description": "Update agent config fields" },
                    { "name": "agents.remove", "description": "Soft-delete an agent (hidden, data retained)" },
                    { "name": "agents.archive", "description": "Archive an agent (recoverable off-board)" },
                    { "name": "agents.unarchive", "description": "Restore an archived agent" },
                    { "name": "agents.handoff", "description": "Hand off memory/wiki/tasks to another agent" },
                    { "name": "agents.set_avatar", "description": "Upload an agent avatar image (data URI)" },
                    { "name": "agents.clear_avatar", "description": "Remove an agent's uploaded avatar" },
                    { "name": "agents.inspect", "description": "Inspect agent details" },
                    { "name": "agents.avatar", "description": "Fetch an agent's uploaded avatar as a data URI (lightweight)" },
                    { "name": "channels.status", "description": "Channel connection status" },
                    { "name": "channels.add", "description": "Add a channel" },
                    { "name": "channels.test", "description": "Test a channel" },
                    { "name": "channels.remove", "description": "Remove a channel" },
                    { "name": "channels.config_get", "description": "Read a channel's behavior settings" },
                    { "name": "channels.config_set", "description": "Write a channel's behavior settings" },
                    { "name": "channels.access_get", "description": "Read a channel's access-control settings" },
                    { "name": "channels.access_set", "description": "Write a channel's access-control settings" },
                    { "name": "channels.pairing_list", "description": "List approved channel pairing subjects" },
                    { "name": "channels.pairing_revoke", "description": "Revoke an approved channel pairing subject" },
                    { "name": "accounts.list", "description": "List accounts" },
                    { "name": "accounts.budget_summary", "description": "Budget overview" },
                    { "name": "accounts.rotate", "description": "Rotate account key" },
                    { "name": "accounts.health", "description": "Account health check" },
                    { "name": "memory.search", "description": "Search agent memory" },
                    { "name": "memory.browse", "description": "Browse recent memory entries" },
                    { "name": "memory.key_facts", "description": "List extracted key insights (P2 Key-Fact Accumulator)" },
                    { "name": "memory.decay_overview", "description": "Memory freshness distribution, fading/most-recalled top-N and accumulation trend" },
                    { "name": "memory.history", "description": "Fact supersession chain (F1 Temporal Memory)" },
                    { "name": "memory.at", "description": "Point-in-time fact lookup (F1 Temporal Memory)" },
                    { "name": "memory.get_at", "description": "Point-in-time fact lookup (D6 alias of memory.at)" },
                    { "name": "memory.graph", "description": "SPO knowledge-graph export for the D6 curation viewer" },
                    { "name": "memory.invalidate_origin", "description": "Destructive: expire all facts from one source (D6 rollback)" },
                    { "name": "memory.forget", "description": "Forget one memory entry (archived, recoverable)" },
                    { "name": "cost.summary", "description": "Cost / cache-efficiency window summary + price-cliff status" },
                    { "name": "cost.agents", "description": "Per-agent cost + cache health" },
                    { "name": "cost.recent", "description": "Recent per-request cost records" },
                    { "name": "cost.by_model", "description": "Per-model cost rollup (requests / tokens / cost per model, costliest first)" },
                    { "name": "cost.by_role", "description": "Measured team-role cost rollup (optionally for one task)" },
                    { "name": "wiki.pages", "description": "List wiki pages for an agent" },
                    { "name": "wiki.read", "description": "Read a wiki page" },
                    { "name": "wiki.auto_pages", "description": "List auto-filed knowledge pages with their source chain (WP5c)" },
                    { "name": "wiki.promote", "description": "Confirm an auto-filed page as curated knowledge (WP5c)" },
                    { "name": "wiki.archive", "description": "Remove an auto-filed page and expire its memory pointer (WP5c)" },
                    { "name": "wiki.share", "description": "Copy an auto-filed page into the shared knowledge base (WP5c)" },
                    { "name": "wiki.search", "description": "Search wiki pages" },
                    { "name": "wiki.lint", "description": "Wiki health check" },
                    { "name": "wiki.stats", "description": "Wiki statistics" },
                    { "name": "shared_wiki.pages", "description": "List shared wiki pages" },
                    { "name": "shared_wiki.read", "description": "Read a shared wiki page" },
                    { "name": "shared_wiki.search", "description": "Search shared wiki" },
                    { "name": "shared_wiki.stats", "description": "Shared wiki statistics" },
                    { "name": "skills.list", "description": "List agent skills" },
                    { "name": "skills.content", "description": "Read skill content" },
                    { "name": "cron.list", "description": "List cron jobs" },
                    { "name": "cron.add", "description": "Add a cron job" },
                    { "name": "cron.pause", "description": "Pause a cron job" },
                    { "name": "cron.remove", "description": "Remove a cron job" },
                    { "name": "cron.run_now", "description": "Run a cron job once now (test execution)" },
                    { "name": "cron.templates", "description": "List built-in office scheduling templates" },
                    { "name": "system.status", "description": "System status" },
                    { "name": "system.doctor", "description": "Health checks" },
                    { "name": "system.doctor_repair", "description": "Health checks with repair hints" },
                    { "name": "models.list", "description": "List available cloud and local models" },
                    { "name": "models.refresh", "description": "Re-probe installed CLIs/APIs for live model lists" },
                    { "name": "runtime.detect", "description": "Detect installed AI runtimes (claude/codex/gemini/antigravity) + Claude OAuth" },
                    { "name": "runtime.install", "description": "Install a missing AI runtime CLI from a hard-coded whitelist (admin)" },
                    { "name": "system.config", "description": "View system config" },
                    { "name": "system.update_config", "description": "Update system config keys by TOML path; returns changes[] and restart_required[] (admin)" },
                    { "name": "config.raw.get", "description": "Read config.toml / inference.toml / an agent.toml as TOML text with secrets masked (admin)" },
                    { "name": "config.raw.set", "description": "Validate and write a raw config file; backup, audit, restart_required[] (admin)" },
                    { "name": "tick.sources.list", "description": "List [[tick.sources]] entries with validation state; header values never returned (admin)" },
                    { "name": "tick.sources.upsert", "description": "Add or update one tick source by id, validated like the boot loader (admin)" },
                    { "name": "tick.sources.remove", "description": "Remove one tick source by id (admin)" },
                    { "name": "delegation.get", "description": "Read the org-wide delegation policy + cross-department pairs (admin)" },
                    { "name": "delegation.set", "description": "Update the delegation policy / cross-department pairs (admin)" },
                    { "name": "system.autostart.status", "description": "Login/boot autostart registration status (admin)" },
                    { "name": "system.autostart.set", "description": "Enable/disable gateway autostart at login/boot (admin)" },
                    { "name": "accounts.add", "description": "Add a new account (provider defaults to anthropic)" },
                    { "name": "accounts.update_budget", "description": "Update account monthly budget" },
                    { "name": "system.version", "description": "Version info" },
                    { "name": "system.check_update", "description": "Check for available updates" },
                    { "name": "system.apply_update", "description": "Download and apply update" },
                    { "name": "heartbeat.status", "description": "Per-agent heartbeat status" },
                    { "name": "heartbeat.trigger", "description": "Manually trigger heartbeat for an agent" },
                    { "name": "mcp.list", "description": "List MCP servers for all agents + catalog" },
                    { "name": "mcp.update", "description": "Add or remove an MCP server for an agent" },
                    { "name": "mcp.import.fetch", "description": "Fetch + security-scan MCP server defs from a GitHub/URL manifest" },
                    { "name": "mcp.import.install", "description": "Install a scanned MCP server def (fail-closed re-scan)" },
                    { "name": "skills.install_request", "description": "File a Skill install request for approval (non-admin)" },
                    { "name": "experts.list", "description": "List installed expert packs (admin)" },
                    { "name": "experts.install", "description": "Install an expert pack from a server-local dir/zip (admin)" },
                    { "name": "experts.remove", "description": "Remove an installed expert pack (admin)" },
                    { "name": "experts.hooks_apply", "description": "Apply the approval decision for a pack's hooks (admin)" },
                    { "name": "experts.catalog", "description": "List built-in industry expert packs available for one-click install (admin)" },
                    { "name": "experts.install_builtin", "description": "Convert + install a built-in industry expert pack (admin)" },
                    { "name": "experts.generate", "description": "LLM-generate a custom expert-pack draft from a guided form (admin)" },
                    { "name": "experts.generate_revise", "description": "Regenerate an expert-pack draft with feedback (admin, max 5 rounds)" },
                    { "name": "experts.install_draft", "description": "Install a generated expert-pack draft via the full security pipeline (admin)" },
                    { "name": "gallery.list", "description": "List curated inspiration-gallery cards (team task examples) for one-click remake (admin)" },
                    { "name": "mcp.install_request", "description": "File an MCP install request for approval (non-admin)" },
                    { "name": "mcp.remote_connect", "description": "Connect a remote MCP server (OAuth / bearer / none) for an agent (admin)" },
                    { "name": "mcp.remote_status", "description": "List connected remote MCP servers, no secrets (admin)" },
                    { "name": "mcp.remote_disconnect", "description": "Delete a remote MCP server's stored credentials (admin)" },
                    { "name": "install_requests.list", "description": "List install requests actionable by the caller (manager+)" },
                    { "name": "install_requests.mine", "description": "The caller's own install requests + status" },
                    { "name": "install_requests.decide", "description": "Approve/deny an install request; executes on final approval" },
                    { "name": "mcp.oauth.providers", "description": "List available OAuth providers and their auth status" },
                    { "name": "mcp.oauth.start", "description": "Start OAuth flow for a provider" },
                    { "name": "mcp.oauth.status", "description": "Check OAuth status for a provider" },
                    { "name": "mcp.oauth.revoke", "description": "Revoke OAuth token for a provider" },
                    { "name": "logs.subscribe", "description": "Subscribe to logs" },
                    { "name": "logs.unsubscribe", "description": "Unsubscribe from logs" },
                    { "name": "security.status", "description": "Security system status" },
                    { "name": "security.credential_hygiene", "description": "Scan config.toml for plaintext credentials (paths only, never values)" },
                    { "name": "security.credential_inventory", "description": "List every credential field with its source (secret:// reference / encrypted / plaintext), never a value" },
                    { "name": "security.credential_cleanup", "description": "Remove plaintext credential fields that already have an encrypted twin" },
                    { "name": "secaudit.reports", "description": "List code security audit reports written by `duduclaw secaudit --save` (shallow summary, newest first)" },
                    { "name": "secaudit.report", "description": "Read one full code security audit report (findings + evidence chains)" },
                    { "name": "secaudit.finding_status", "description": "Record an operator's confirm/suppress/refute decision on a security audit finding" },
                    { "name": "analytics.summary", "description": "Analytics summary for a period" },
                    { "name": "analytics.conversations", "description": "Daily conversation counts" },
                    { "name": "analytics.cost_savings", "description": "Monthly cost savings" },
                    { "name": "migrate.scan", "description": "Preview a migration from OpenClaw/Hermes/Paperclip (dry-run)" },
                    { "name": "migrate.apply", "description": "Apply a migration from OpenClaw/Hermes/Paperclip" },
                    { "name": "search.query", "description": "Cross-source search (⌘K) over conversations, files, memory and knowledge (I-5)" },
                    { "name": "device.status", "description": "Appliance CPU/RAM/disk/temperature/uptime/network snapshot (admin, appliance-only)" },
                    { "name": "device.network", "description": "Read network interfaces; setting a static IP is not implemented yet (admin, appliance-only)" },
                    { "name": "device.update_status", "description": "Check for an available OS update via systemd-sysupdate (admin, appliance-only)" },
                    { "name": "device.update_check", "description": "Check the configured update source for a newer OS version (signed manifest only, no download) (admin, appliance-only)" },
                    { "name": "device.update_apply", "description": "Install the newest available OS update (admin, appliance-only)" },
                    { "name": "device.update_rollback", "description": "Roll back to the previous OS version and reboot (admin, appliance-only, destructive: requires confirm)" },
                    { "name": "device.boot_assessment", "description": "Report systemd's automatic boot assessment state for the running version (admin, appliance-only, read-only)" },
                    { "name": "device.backup_create", "description": "Archive the device's writable data partition for download (admin, appliance-only)" },
                    { "name": "device.backup_schedule_get", "description": "Read the scheduled-backup config (admin, appliance-only)" },
                    { "name": "device.backup_schedule_set", "description": "Update the scheduled-backup config (schedule_enabled/interval_hours/retention_count) (admin, appliance-only)" },
                    { "name": "device.backup_list", "description": "List scheduled backups stored under <home>/backups/ (admin, appliance-only)" },
                    { "name": "device.backup_delete", "description": "Delete one scheduled backup file (admin, appliance-only)" },
                    { "name": "device.backup_restore", "description": "Stage an uploaded backup for device-migration restore on next boot (admin, appliance-only, destructive: requires confirm)" },
                    { "name": "device.factory_reset", "description": "Wipe device state and re-provision on next boot; optional clear_network also clears saved Wi-Fi credentials (default: kept) (admin, appliance-only, destructive: requires confirm)" },
                    { "name": "device.power", "description": "Restart or shut down the device (admin, appliance-only, destructive: requires confirm)" },
                    { "name": "device.power_local", "description": "Lock-screen power menu: restart or shut down the device (no login, appliance-only, loopback-only, rate limited)" },
                    { "name": "network.wifi_scan", "description": "Scan for Wi-Fi networks via iwd D-Bus (admin, appliance-only)" },
                    { "name": "network.wifi_connect", "description": "Connect to a Wi-Fi network by SSID, with an optional passphrase (admin, appliance-only, audited)" },
                    { "name": "network.wifi_forget", "description": "Delete a stored Wi-Fi credential by SSID (admin, appliance-only, audited)" },
                    { "name": "network.status", "description": "Wi-Fi link state, IP info, and internet/captive-portal connectivity (admin, appliance-only)" },
                    { "name": "device.about", "description": "OS/kernel/hostname/gateway-version identity snapshot for the system-settings app (admin, appliance-only)" },
                    { "name": "device.timedate", "description": "Timezone, local/UTC clock, and NTP sync status (admin, appliance-only)" },
                    { "name": "device.timedate_set", "description": "Set timezone and/or enable/disable NTP (admin, appliance-only, audited)" },
                    { "name": "network.wired_status", "description": "Wired (Ethernet) link state, IP info, and the persisted desired static config, if any (admin, appliance-only)" },
                    { "name": "network.wired_config", "description": "Set the wired interface to DHCP or a static IPv4 config (admin, appliance-only, audited)" },
                    { "name": "maintenance.enable", "description": "Turn on maintenance mode for a bounded TTL (unlocks SSH and/or full raw diagnostic detail) (admin, appliance-only, destructive: requires confirm + re-auth)" },
                    { "name": "maintenance.disable", "description": "Turn off maintenance mode immediately (admin, appliance-only, audited)" },
                    { "name": "maintenance.status", "description": "Whether maintenance mode is currently active, remaining time, and which sub-capabilities are unlocked (admin, appliance-only, read-only)" },
                    { "name": "maintenance.history", "description": "Paginated maintenance-mode audit history (admin, appliance-only, read-only)" },
                ]
            }),
        )
    }

    /// `tools.builtin_catalog` — catalog of built-in agent tools (DuDuClaw MCP
    /// tools qualified as `mcp__duduclaw__<name>`, plus native Claude Code
    /// tools) that populates the capability editor's "add from built-in tools"
    /// picker for `allowed_tools` / `denied_tools`. Sourced from
    /// `duduclaw_core::tool_catalog` — the single source of truth whose scope
    /// column is drift-tested against `mcp_auth::tool_requires_scope`. Distinct
    /// from `tools.catalog`, which enumerates dashboard RPC methods.
    pub(crate) fn handle_tools_builtin_catalog(&self) -> WsFrame {
        let tools = duduclaw_core::tool_catalog::builtin_tool_catalog();
        match serde_json::to_value(&tools) {
            Ok(v) => WsFrame::ok_response("", json!({ "tools": v })),
            Err(e) => WsFrame::error_response("", &format!("tool catalog serialize failed: {e}")),
        }
    }
}
