#!/usr/bin/env bash
# Generate the app icon set referenced by tauri.conf.json > bundle.icon (§D0).
#
# Primary path: `cargo tauri icon` (produces the full cross-platform set incl.
# the Windows .ico). Fallback path (macOS, no Tauri CLI): `sips` + `iconutil`
# generate the PNGs and the .icns; the .ico still needs ImageMagick / the Tauri
# CLI, so the fallback warns instead of pretending it's complete.
#
# Source: a square >=1024x1024 PNG of the brand paw mark.
#   ./gen-icons.sh [path/to/source-1024.png]
# Defaults to web/public/paw-1024.png.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT"

SRC="${1:-web/public/paw-1024.png}"
OUT="src-tauri/icons"

if [[ ! -f "$SRC" ]]; then
  echo "Source icon not found: $SRC" >&2
  echo "Provide a square >=1024x1024 PNG of the paw mark (brand amber background)." >&2
  exit 1
fi
mkdir -p "$OUT"

# --- Primary: cargo tauri icon (preferred — also emits the Windows .ico) ------
if command -v cargo-tauri >/dev/null 2>&1 || cargo tauri --version >/dev/null 2>&1; then
  echo "Using 'cargo tauri icon' (full cross-platform set)…"
  ( cd src-tauri && cargo tauri icon "../$SRC" )
  echo "Generated icon set in $OUT/"
  exit 0
fi

# --- Fallback: sips + iconutil (macOS only; no .ico) --------------------------
if ! command -v sips >/dev/null 2>&1; then
  echo "Neither 'cargo tauri' nor 'sips' is available — install the Tauri CLI:" >&2
  echo "  cargo install tauri-cli --version '^2'" >&2
  echo "then re-run, or run on macOS where 'sips' exists." >&2
  exit 1
fi

echo "Tauri CLI absent — falling back to sips/iconutil (PNGs + .icns only)…"
sips -z 32 32     "$SRC" --out "$OUT/32x32.png"        >/dev/null
sips -z 128 128   "$SRC" --out "$OUT/128x128.png"      >/dev/null
sips -z 256 256   "$SRC" --out "$OUT/128x128@2x.png"   >/dev/null

if command -v iconutil >/dev/null 2>&1; then
  ICONSET="$(mktemp -d)/icon.iconset"
  mkdir -p "$ICONSET"
  for s in 16 32 128 256 512; do
    sips -z "$s" "$s"       "$SRC" --out "$ICONSET/icon_${s}x${s}.png"      >/dev/null
    sips -z $((s*2)) $((s*2)) "$SRC" --out "$ICONSET/icon_${s}x${s}@2x.png" >/dev/null
  done
  iconutil -c icns "$ICONSET" -o "$OUT/icon.icns"
  rm -rf "$(dirname "$ICONSET")"
  echo "Generated $OUT/{32x32,128x128,128x128@2x}.png + icon.icns"
fi

echo "WARNING: Windows icon.ico was NOT generated by the fallback path." >&2
echo "         Use 'cargo tauri icon' or ImageMagick to produce icons/icon.ico" >&2
echo "         before bundling for Windows." >&2
